objective:
  - Bilevel Optimization
dataset:
  - mnist[ratio=0.5]
solver:
  - SABA[batch_size=64,eval_freq=512,framework=none,mode_init_memory=zero,outer_ratio=1.0,step_size=0.0001,random_state=[1],framework=none]
  - SOBA[batch_size=64,eval_freq=512,framework=none,outer_ratio=0.0001,step_size=0.0001,random_state=[1],framework=none]
  - PAGE[batch_size=64,eval_freq=512,framework=none,outer_ratio=0.005,step_size=0.1,random_state=[1],r_z=2.5,framework=none]
n-repetitions: 1
max-runs: 100
timeout: 900
output: datacleaning0_5
